spec_version: app/0.1
title: Application
summary: My sample app
version: 0.1.0
terms_of_service: 
model_directory: models # directory to model YAML spec, relative to app.yaml
libs_directory: libs # directory to libs directory, relative to app.yaml
databases: # sqlalchemy database connections to create for the app
  - name: default 
    type: sqlalchemy
    url: sqlite:///./database.sqlite
#    url_env: DB_URL # environment variable that stores the database url
#object_stores:
#  - name: default
#    type: minio # type of object storage, we only support MinIO or MinIO compatible servers for now.
#    endpoint_url_env: S3_ENDPOINT
#    access_key_env: S3_ACCESS_KEY # environment variable that stores the access key
#    secret_key_env: S3_SECRET_KEY # environment variable that stores the secret key
#
views: 
  extensions: # view registry on the root of the app. use this place add views on your app that is not attached to a model
    '/+hello':
      method: 'GET'
      handler:
        code: |
          def function(request: Request):
              return {'message': 'hello world'}
